tronprotocol/tips

TWP-001.md

Tron Deterministic Wallet Proposal - Key Derivation Methods for Tron Accounts with BIP39

TIP001 - Tron Wallet Proposal (TWP)

---

tip-12.md

add tip-12 for event subscribe

---

tip-28.md

Update tip 28.md

---

template.md

update the template according to read.me

update the template according to read.me

---

README.md
template.md

Readme revise

---

README.md
tip-28.md

update tip28 status

---

template.md
tip-19.md

revise tips, add descriptions.

add description of tip template

---

README.md

add descriptions

---

p2p/001-Node-Discover-Protocol.md

add 001-Node-Discover-Protocol

add 001-Node-Discover-Protocol

---

tp/p2p/002-Node-State-Machine.md
tp/p2p/003-Node-Scoring-Policy.md

add node state machine tp and node scoring policy tp

Node state machine

---

tp/p2p/003-Node-Scoring-Policy.md

update node scoring policy tp

---

tp/p2p/002-Node-State-Machine.md
tp/p2p/003-Node-Scoring-Policy.md

update node state machine tp

---

tip-135.md
tip-shielded-contract.md

The TIP define the  shielded token contract, which can  transfer the public TRC-20 token to shielded token

TIP-135: add the shielded token contract

---

tip-135.md

make the input and output size in the range [1, 2]

TIP-135: update the transfer method

---

README.md

Update README.md to add 137 and 138

Update README.md to add 137 and 138

---

README.md

Change TIP51 status to Final

---

README.md
tip-135.md
tip-137.md
tip-138.md

include TIP-135, TIP-137, TIP-138

Update the status to be final

---

tip-158.md

STAKE instructions

---

tip-120.md

provide unified signature encoding standard

 TIP-120 signauture encoding specification

---

tip-174.md
tip-175.md
tip-176.md

change category to VM, change status to LastCall for tip 174,175,176

change category to VM, change status to LastCall

---

tip-127.md

change Tip127 status to "LASTCALL"

change Tip status

---

tip-209.md

add tip-209 about solidity0.6.0

add tip-209 about solidity0.6.0

---

README.md
tip-269.md
tip-281.md

Optimize query performance
Optimizing processBlock performance

Optimize query performance

---

README.md
tip-298.md

Optimize c++ version of levelDB startup, reduce memory usage and time.

add tip-298

---

README.md
tip-295.md

modify tip-295 to Last Call

---

README.md
tip-391.md

Add TIP-391

---

README.md
tip-440.md

Add TIP-440

---

README.md
tip-461.md

add TIP-461

---

README.md
tip-387.md
tip-476.md

add TIP-387 and TIP-476

---

tip-387.md

fix TIP-387

---

README.md
tip-465.md

add TIP-465

---

README.md
tip-491.md

Add TIP-491: Dynamic Energy Model

Add TIP-491: Dynamic Energy Model

---

tip-534.md

docs(tip): update TIP-534

---

tip-16.md

alialkhtri3@gmail.com

---

tip-16.md

Reverts tronprotocol/tips#743
the last commit is invalid

Revert "alialkhtri3@gmail.com"
